<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Jeff32819DLL.TemplateFiller20</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.3.0</Version>
    <PackageId>Jeff32819DLL.TemplateFiller20</PackageId>
  </PropertyGroup>
</Project>